[package]
name = "aneubeck-daacfind"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.2", features = ["derive"] }  # MIT or Apache-2.0
aneubeck-daachorse = { path = ".." }  # MIT or Apache-2.0
termcolor = "1.1"  # Unlicense or MIT
